'use client';
import { ArrowUpRight, LockKeyhole } from 'lucide-react';
import { useAnimeScope } from '@/hooks/useAnimeScope';
import { sectionAnimation } from '@/lib/animations/scroll';
import { useLaunch } from '@/components/ui/LaunchProvider';
export function MissionSection() {
  const root = useAnimeScope<HTMLElement>(sectionAnimation), launch = useLaunch();
  return <section ref={root} className="mission-section section-wrap" id="missions"><div className="section-kicker"><span>03 / MISSION ARCHIVE</span><span><i className="status-dot"/> 1 SIGNAL AVAILABLE</span></div><div className="mission-heading"><h2>THREE SIGNALS.<br/><span>ONE ACTIVE.</span></h2><p>Somewhere out there,<br/>something is still transmitting.</p></div><div className="mission-space"><svg className="mission-orbits" viewBox="0 0 1200 420" fill="none" aria-hidden="true"><ellipse cx="370" cy="305" rx="460" ry="200" transform="rotate(-18 370 305)"/><ellipse cx="750" cy="140" rx="350" ry="150" transform="rotate(15 750 140)" strokeDasharray="2 8"/><path d="M0 380 1200 70" strokeDasharray="2 10"/></svg><button className="mission-node mission-active" onClick={launch}><div className="planet planet-one"><i/><span className="planet-ring"/></div><div className="mission-caption"><span className="mission-id">MISSION 001 <b>OPEN CHANNEL</b></span><h3>ORBITAL<br/>RUINS <ArrowUpRight size={25}/></h3><span>INTERCEPT SIGNAL</span></div></button><div className="mission-node mission-locked mission-two"><div className="planet planet-two"/><div className="mission-caption"><span className="mission-id">MISSION 002</span><h3>DEEP SIGNAL</h3><span><LockKeyhole size={11}/> SIGNAL REQUIRED</span></div></div><div className="mission-node mission-locked mission-three"><div className="planet planet-three"/><div className="mission-caption"><span className="mission-id">MISSION 003</span><h3>THE MACHINE</h3><span><LockKeyhole size={11}/> SIGNAL REQUIRED</span></div></div><span className="mission-coordinate">SECTOR 004 / UNCHARTED SPACE</span></div></section>;
}
